### ISSUE TITLE
folder name

### ISSUE THREAD

**Issue by sebasvisser** [getgrav/grav-plugin-custom-css#3]
If i change the folder name to custom-css it makes sure that the plugin is shown within the admin menu.
However, it breaks the website, renaming the folder to grav-plugin-custom-css-develop fixes the site (even though it doesn't fix the custom css that i was trying to insert) but makes the plugin disappear from the adminpage...
See log downbelow:

```
[2016-08-02 21:46:20] grav.NOTICE: Invalid slug set in YAML frontmatter: /Ervaring en Waarneming => ervaring en waarneming [] []
[2016-08-02 22:23:30] grav.NOTICE: Invalid slug set in YAML frontmatter: /Ervaring en Waarneming/Communicatie en Ruis => communicatie en ruis [] []
[2016-08-03 00:31:38] grav.NOTICE: Invalid slug set in YAML frontmatter: /Ervaring en Waarneming/ Reflectie Ervaring en Waarneming =>  reflectie ervaring en waarneming [] []
[2016-08-03 00:32:02] grav.NOTICE: Invalid slug set in YAML frontmatter: /Ervaring en Waarneming/ Reflectie Ervaring en Waarneming =>  reflectie ervaring en waarneming [] []
[2016-08-03 09:37:30] grav.CRITICAL: Page Not Found - Trace: #0 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\pimple\pimple\src\Pimple\Container.php(113): Grav\Common\Service\PageServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #1 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\user\plugins\simplesearch\simplesearch.php(83): Pimple\Container->offsetGet('page') #2 [internal function]: Grav\Plugin\SimplesearchPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #5 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #6 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(297): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', NULL) #7 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Processors\PagesProcessor.php(18): Grav\Common\Grav->fireEvent('onPagesInitiali...') #8 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(121): Grav\Common\Processors\PagesProcessor->process() #9 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(383): Grav\Common\Grav->Grav\Common\{closure}() #10 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #11 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(359): call_user_func_array(Object(Closure), Array) #12 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #13 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->measureTime('pages', 'Pages', Object(Closure)) #14 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\index.php(45): Grav\Common\Grav->process() #15 {main} [] []
[2016-08-03 12:26:42] grav.NOTICE: Invalid slug set in YAML frontmatter: /Ervaring en Waarneming/ Reflectie Ervaring en Waarneming =>  reflectie ervaring en waarneming [] []
[2016-08-04 09:36:50] grav.NOTICE: Invalid slug set in YAML frontmatter: /De Wereld Anders Bekeken/Hoeden van de Bono => hoeden van de bono [] []
[2016-08-04 09:37:28] grav.NOTICE: Invalid slug set in YAML frontmatter: /De Wereld Anders Bekeken/Hoeden van de Bono => hoeden van de bono [] []
[2016-08-04 09:38:35] grav.NOTICE: Invalid slug set in YAML frontmatter: /De Wereld Anders Bekeken/Hoeden van de Bono => hoeden van de bono [] []
[2016-08-04 09:39:12] grav.NOTICE: Invalid slug set in YAML frontmatter: /De Wereld Anders Bekeken/Hoeden van de Bono => hoeden van de bono [] []
[2016-08-04 10:00:29] grav.WARNING: Plugin 'grav-plugin-custom-css-develop' enabled but not found! Try clearing cache with `bin/grav clear-cache` [] []
[2016-08-04 10:00:30] grav.NOTICE: Invalid slug set in YAML frontmatter: /De Wereld Anders Bekeken/Hoeden van de Bono => hoeden van de bono [] []
[2016-08-04 10:00:30] grav.WARNING: Plugin 'grav-plugin-custom-css-develop' enabled but not found! Try clearing cache with `bin/grav clear-cache` [] []
[2016-08-04 10:00:32] grav.WARNING: Plugin 'grav-plugin-custom-css-develop' enabled but not found! Try clearing cache with `bin/grav clear-cache` [] []
[2016-08-04 10:00:32] grav.WARNING: Plugin 'grav-plugin-custom-css-develop' enabled but not found! Try clearing cache with `bin/grav clear-cache` [] []
[2016-08-04 10:00:35] grav.WARNING: Plugin 'grav-plugin-custom-css-develop' enabled but not found! Try clearing cache with `bin/grav clear-cache` [] []
[2016-08-04 10:00:37] grav.WARNING: Plugin 'grav-plugin-custom-css-develop' enabled but not found! Try clearing cache with `bin/grav clear-cache` [] []
[2016-08-04 10:06:47] grav.CRITICAL: Invalid argument supplied for foreach() - Trace: #0 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\user\plugins\custom-css\custom-css.php(42): Whoops\Run->handleError(2, 'Invalid argumen...', 'C:\\Users\\sebas\\...', 42, Array) #1 [internal function]: Grav\Plugin\CustomCSSPlugin->onAssetsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #2 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #4 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #5 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(297): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAssetsInitial...', NULL) #6 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Processors\AssetsProcessor.php(18): Grav\Common\Grav->fireEvent('onAssetsInitial...') #7 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(121): Grav\Common\Processors\AssetsProcessor->process() #8 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(383): Grav\Common\Grav->Grav\Common\{closure}() #9 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('assets', 'Assets', Object(Closure)) #10 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(359): call_user_func_array(Object(Closure), Array) #11 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #12 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->measureTime('assets', 'Assets', Object(Closure)) #13 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\index.php(45): Grav\Common\Grav->process() #14 {main} [] []
[2016-08-04 10:06:53] grav.CRITICAL: Invalid argument supplied for foreach() - Trace: #0 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\user\plugins\custom-css\custom-css.php(42): Whoops\Run->handleError(2, 'Invalid argumen...', 'C:\\Users\\sebas\\...', 42, Array) #1 [internal function]: Grav\Plugin\CustomCSSPlugin->onAssetsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #2 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #4 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #5 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(297): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAssetsInitial...', NULL) #6 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Processors\AssetsProcessor.php(18): Grav\Common\Grav->fireEvent('onAssetsInitial...') #7 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(121): Grav\Common\Processors\AssetsProcessor->process() #8 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(383): Grav\Common\Grav->Grav\Common\{closure}() #9 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('assets', 'Assets', Object(Closure)) #10 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(359): call_user_func_array(Object(Closure), Array) #11 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #12 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->measureTime('assets', 'Assets', Object(Closure)) #13 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\index.php(45): Grav\Common\Grav->process() #14 {main} [] []
[2016-08-04 10:07:08] grav.CRITICAL: Invalid argument supplied for foreach() - Trace: #0 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\user\plugins\custom-css\custom-css.php(42): Whoops\Run->handleError(2, 'Invalid argumen...', 'C:\\Users\\sebas\\...', 42, Array) #1 [internal function]: Grav\Plugin\CustomCSSPlugin->onAssetsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #2 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #4 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #5 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(297): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAssetsInitial...', NULL) #6 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Processors\AssetsProcessor.php(18): Grav\Common\Grav->fireEvent('onAssetsInitial...') #7 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(121): Grav\Common\Processors\AssetsProcessor->process() #8 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(383): Grav\Common\Grav->Grav\Common\{closure}() #9 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('assets', 'Assets', Object(Closure)) #10 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(359): call_user_func_array(Object(Closure), Array) #11 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #12 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->measureTime('assets', 'Assets', Object(Closure)) #13 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\index.php(45): Grav\Common\Grav->process() #14 {main} [] []
[2016-08-04 10:09:34] grav.NOTICE: Invalid slug set in YAML frontmatter: /De Wereld Anders Bekeken/Hoeden van de Bono => hoeden van de bono [] []
[2016-08-04 10:09:54] grav.CRITICAL: Invalid argument supplied for foreach() - Trace: #0 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\user\plugins\custom-css\custom-css.php(42): Whoops\Run->handleError(2, 'Invalid argumen...', 'C:\\Users\\sebas\\...', 42, Array) #1 [internal function]: Grav\Plugin\CustomCSSPlugin->onAssetsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #2 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #4 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #5 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(297): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAssetsInitial...', NULL) #6 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Processors\AssetsProcessor.php(18): Grav\Common\Grav->fireEvent('onAssetsInitial...') #7 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(121): Grav\Common\Processors\AssetsProcessor->process() #8 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(383): Grav\Common\Grav->Grav\Common\{closure}() #9 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('assets', 'Assets', Object(Closure)) #10 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(359): call_user_func_array(Object(Closure), Array) #11 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #12 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->measureTime('assets', 'Assets', Object(Closure)) #13 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\index.php(45): Grav\Common\Grav->process() #14 {main} [] []
[2016-08-04 10:10:50] grav.CRITICAL: Invalid argument supplied for foreach() - Trace: #0 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\user\plugins\custom-css\custom-css.php(42): Whoops\Run->handleError(2, 'Invalid argumen...', 'C:\\Users\\sebas\\...', 42, Array) #1 [internal function]: Grav\Plugin\CustomCSSPlugin->onAssetsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #2 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #4 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #5 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(297): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAssetsInitial...', NULL) #6 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Processors\AssetsProcessor.php(18): Grav\Common\Grav->fireEvent('onAssetsInitial...') #7 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(121): Grav\Common\Processors\AssetsProcessor->process() #8 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(383): Grav\Common\Grav->Grav\Common\{closure}() #9 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('assets', 'Assets', Object(Closure)) #10 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(359): call_user_func_array(Object(Closure), Array) #11 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #12 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\system\src\Grav\Common\Grav.php(122): Grav\Common\Grav->measureTime('assets', 'Assets', Object(Closure)) #13 C:\Users\sebas\Dropbox\MilkyWebs\Lokaal Gebouwen\gravcoach.dev\index.php(45): Grav\Common\Grav->process() #14 {main} [] []
```

**Comment by flaviocopes** [comment]
Plugins are meant to be hosted in the folder that they come when installed, you cannot really rename them unless renaming the plugin's main PHP file and class, or the plugin is not executed at all (this is what happens when you rename it).

Quite sure I fixed the issue in the latest release of the plugin, the problem was when no CSS file was added to the list of CSS files to load - you have the latest release?
